apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    tier: frontend
  type: ClusterIP
